# Generated by Django 3.0.8 on 2020-11-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCN_App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestransaction',
            old_name='student_name',
            new_name='student_name1',
        ),
    ]
