# Generated by Django 3.0.8 on 2020-11-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCN_App1', '0002_auto_20201103_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestransaction',
            old_name='student_name1',
            new_name='student_name',
        ),
    ]
